### ISSUE TITLE
Need to alter time in minimal `send_mail`.

### ISSUE THREAD

**Issue by denis-trofimov** [denis-trofimov/learnpython#5]
```py
(env) denis@joy:~/p/learnpython/landing_page$ python manage.py test
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.A mandrill error occurred: <class 'mandrill.ValidationError'> - Validation error: {"send_at":"Please enter a valid date\/time"}
E
======================================================================
ERROR: test_send_mail (timepad_mail.tests.MandrillSendTest)
Send a new transactional message through Mandrill.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/denis/p/learnpython/landing_page/timepad_mail/tests.py", line 73, in test_send_mail
    responce = send_mail(payload)
  File "/home/denis/p/learnpython/landing_page/timepad_mail/send_mail_mandrill.py", line 44, in send_mail
    send_at='example send_at'
  File "/home/denis/p/learnpython/env/lib/python3.6/site-packages/mandrill.py", line 1392, in send
    return self.master.call('messages/send', _params)
  File "/home/denis/p/learnpython/env/lib/python3.6/site-packages/mandrill.py", line 173, in call
    raise self.cast_error(result)
mandrill.ValidationError: Validation error: {"send_at":"Please enter a valid date\/time"}

----------------------------------------------------------------------
Ran 2 tests in 131.260s

FAILED (errors=1)
Destroying test database for alias 'default'...
```

**Comment by denis-trofimov** [comment]
[{'email': 'denistrofimov@pythonmachinelearningcv.com', 'status': 'sent', '_id': 'f0d5302b4aab4b5c84d14891af611c15', 'reject_reason': None}]
